spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ley1996/spring-cloud-study.git
          search-paths: config-server
          username: 海渊
          password: liu1234567
        health:
          repositories:
           check:
            name: config-server
            label: master
            profiles: v1

server:
  port: 9099